apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: evergreen.com
      http:
        paths:
          - path: /api/topics
            pathType: Prefix
            backend:
              service:
                name: topics-srv
                port:
                  number: 8000
          - path: /api/topics/(.+)/submissions
            pathType: Prefix
            backend:
              service:
                name: submissions-srv
                port:
                  number: 8000
          - path: /api/submissions/(.+)/comments
            pathType: Prefix
            backend:
              service:
                name: comments-srv
                port:
                  number: 8000
          - path: /api/comments/(.+)/comments
            pathType: Prefix
            backend:
              service:
                name: comments-srv
                port:
                  number: 8000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 1234
