apiVersion: apps/v1
kind: Deployment
metadata:
  name: submissions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submissions
  template:
    metadata:
      labels:
        app: submissions
    spec:
      containers:
        - name: submissions
          image: skookumchoocher/submissions
          env:
            - name: MONGO_URI
              value: "mongodb://submissions-mongo-srv:27017/submissions"
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: submissions-srv
spec:
  selector:
    app: submissions
  ports:
    - name: submissions
      protocol: TCP
      port: 8000
      targetPort: 8000
